#ifndef BUTTON_H
#define BUTTON_H

#include "gpio.h"

#define BUTTON_SET_GROUP GPIOB
#define BUTTON_SET_PIN 7

#define BUTTON_MODE_GROUP GPIOB
#define BUTTON_MODE_PIN 6

#define BUTTON_GET(_group, _pin) (!GPIO_GET(_group, _pin))

#define BUTTON_SET   BUTTON_GET(BUTTON_SET_GROUP,   BUTTON_SET_PIN)
#define BUTTON_MODE  BUTTON_GET(BUTTON_MODE_GROUP,  BUTTON_MODE_PIN)

#endif // BUTTON_H
